export const ComicsActionTypes = {
    FETCH_COMICS_GET_ALL:"FETCH_COMICS_GET_ALL",
    FETCH_COMICS_Get_Comics_Pagination:"FETCH_COMICS_PAGINATION",
    FETCH_COMICS_SEARCH:"FETCH_COMICS_GET_SEARCH",
    FETCH_COMICS_SEARCH_ERROR:"FETCH_COMICS_SEARCH_ERROR",
    FETCH_COMICS_SEARCH_TITLE:"FETCH_COMICS_SEARCH_TITLE",
    FETCH_COMICS_SEARCH_EMPTY:"FETCH_COMICS_SEARCH_EMPTY",
    FETCH_COMICS_TO_LOCAL_STORAGE:"FETCH_COMICS_TO_LOCAL_STORAGE",
    FETCH_COMICS_ADD_CART:"FETCH_COMICS_ADD_CART"
}